### ISSUE TITLE
[v1] Does this plugin support URP?

### ISSUE THREAD

**Issue by ShenKang4181** [mob-sakai/SoftMaskForUGUI#110]
Does this plugin support URP?

**Comment by AndrewSpalato-FGMNT** [comment]
Any update on this? Would like to have this on URP

**Comment by ShenKang4181** [comment]
> 这事有进一步更新吗？想在URP上拥有这个

no

**Comment by Noblauch** [comment]
Hey @ShenKang4181 we are using softmask with URP, it doesn't support shader graph, and nesting soft masks has been an issue for us, but that is a general problem. Other than that soft mask works just fine.
Otherwise I would use it again, despite these problems, there is nothing on the market that I found that is able to do that.
The fact that shader graph is not supported is a real bummer for us, but hey, what are the options? ;)

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
