### ISSUE TITLE
[v1] Soft mask problem with default mask and resolution change

### ISSUE THREAD

**Issue by Andrea332** [mob-sakai/SoftMaskForUGUI#157]
I have this strange problem when i'm using the unity default mask and the soft mask at the same time, for example when i change resolution of the game the soft mask and everything below it disappeard.

1. Open a new Unity scene
2. Create 2 identical Canvas with an image in it and another image inside the image itself
![image](https://github.com/mob-sakai/SoftMaskForUGUI/assets/74671832/2c798354-6b5a-4be8-b525-5cc1fafc6b8a)
3. On one canvas uses the soft mask components and on the other use the default unity mask
4. Now change the resolution and you will se the soft mask disappeared 
5. It returns working when you disable and re enable the soft maks component

Using a unity default mask should not impact on other soft mask in the scene or prefab

 - Version 1.0.2
 - Platform: WebGL
 - Unity version: 2021.3.25f1
 - Build options: URP, IL2CPP

**Comment by colindefais** [comment]
Hey, I have got the same issue in my project.

I have discovered that de-activating and re-activating a parent of the broken SoftMask GameObjects fix them.

So I have just made a dirty workaround with the following script.
It simply de-activate and re-activate its own gameObject when a RectTransformDimensionsChange happen.

Of course you have to put this Script on a parent of the broken SoftMask GameObjects.

```cs
using UnityEngine;

[HelpURL("https://github.com/mob-sakai/SoftMaskForUGUI/issues/157")]
public class ReActivateOnResize : MonoBehaviour {

    void Start() { }

    void OnRectTransformDimensionsChange() {
        if(isActiveAndEnabled) {
            gameObject.SetActive(false);
            gameObject.SetActive(true);
        }
    }

}
```

This is not perfect:
- the GameObjects disappear temporally while  the window is resized
- side effects might occur with other Scripts/UI components expecting the GameObjects to be active

Of course instead of using my script you can replace all default Unity Masks by SoftMasks, but in my case I prefer using SoftMasks only when necessary (to avoid putting SoftMaskable components everywhere).

**Comment by renee0506** [comment]
I resolved this issue by adding 

```
protected void OnRectTransformDimensionsChange()
{
   OnValidate();
}
```
to SoftMaskable.cs

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
