### ISSUE TITLE
[v1] All SoftMasks disappear when screen orientation is changed

### ISSUE THREAD

**Issue by flowerhouse-dev** [mob-sakai/SoftMaskForUGUI#161]
**Describe the bug**
Changing the screen orientation makes all SoftMasks disappear. Buffers seem to be updating correctly.

**To Reproduce**
Make sure `Player Settings > Resolution and Presentation > Default Orientation` is set to `Auto Rotation`

In the editor:
1. Install Device Simulator package
2. Run demo from sample
3. Rotate orientation using the buttons from the simulator
4. SoftMasks disappear

On device:
1. Build demo from sample
2. Rotate orientation of device
3. SoftMasks disappear

**Expected behavior**
SoftMasks should be updated similar to it updating when the resolution is changed.

**Screenshots**
<img width="579" alt="afbeelding" src="https://github.com/mob-sakai/SoftMaskForUGUI/assets/8613132/77f9fe18-e76b-45e1-a4ab-fcf1b48a331c">

<img width="468" alt="afbeelding" src="https://github.com/mob-sakai/SoftMaskForUGUI/assets/8613132/42f73966-743f-4d51-b528-5e7b113560ea">

**Environment (please complete the following information):**
 - Version 1.0.2
 - Platform: Editor Windows & Mac, Standalone iOS & Android
 - Unity version: 2021.3.31f1
 - Build options: Probably not relevant

**Additional context**
Also tested with the changes from #151 but that does not fix it.
Tried some workarounds with disabling & enabling the component, but that only works in the editor.

**Comment by jhclaura** [comment]
Having the same issue with the demo app, it doesn't work in Android Landscape mode.
It seems this issue is back? https://github.com/mob-sakai/SoftMaskForUGUI/issues/46
Would love to use this in Android Landscape mode, hope it'd be an easy fix... thank you @mob-sakai !

**Comment by flowerhouse-dev** [comment]
We made a workaround that disables the canvas for one frame after orientation change. Not ideal but it works for now.

**Comment by MarkZaytsev** [comment]
I can confirm the bug. To reproduce it:

- In editor mode, put a soft masked image on the scene.
- In runtime, go to this scene from another one, using `LoadSceneAsync`
- During transition, change screen orientation. In my case I was changing it from portrait to landscape. I change orientation on `Awake` callback from a script that is part of the destination scene.
- On any devices, it almost always guaranteed to have the bug in soft mask. Sometimes I could reproduce it in the Editor on Simulator, but not as reliable as on a device.

 If I reload the scene, not changing the orientation, then everything works fine. From debugging, I can see that soft mask handled screen orientation change, got rebuild everything after device created new frame buffer, with correct projection matrices. But for some reason image just doesn't show. I had everything logged frame by frame. 
I have a strong feeling that something just got cached and not updated somewhere in the script or shader parameters.

Unfortunately I was limited in time I can spare for debugging, so I had to go with a workaround. Simply disabling softmask if screen orientation happened and enabling it 10 frames later. With a smaller amount of frames there is a chance that softmask still not work. This workaround is ugly, but does the job.

Important thing to note. Initially I tired to force rebuild the mask, instead of disabling the script. Using `hasChanhed` flag. It didn't work. 

```c#
    private ScreenOrientation _cachedOrientation;

    private async void LateUpdate()
    {
        if (_cachedOrientation == Screen.orientation)
            return;
    
        enabled = false;
        _cachedOrientation = Screen.orientation;
    
        await UniTask.DelayFrame(10);
        if (this == null)
            return;
    
        enabled = true;
    }
```

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by MarkZaytsev** [comment]
To everyone looking for a workaround. I've updated my solution, feel free to use it. I placed it on a static dedicated game object on starting scene. Works just fine. It will affect only SoftMask components that were part of the scene when scene was loaded
and were enabled. I think 7 frames delay should be enough.

Keep in mind that this works only in case if screen orientation change happened after you loaded to the scene, in my case in `Awake` callback. Otherwise you will need to modify the script.

Also I'm using Unity 2023.1.3f1

```c#
internal class ScreenOrientationBugFixer : MonoBehaviour
{
    private static bool _isInitialized;
    private ScreenOrientation _cachedOrientation;

    private void Awake()
    {
        if (_isInitialized)
        {
            Destroy(gameObject);
            return;
        }

        DontDestroyOnLoad(gameObject);
        StartCoroutine(MonitorOrientationChange());
        _isInitialized = true;
    }

    private IEnumerator MonitorOrientationChange()
    {
        _cachedOrientation = Screen.orientation;

        var wait = new WaitForEndOfFrame();
        while (true)
        {
            yield return wait;

            if (_cachedOrientation == Screen.orientation)
                continue;

            _cachedOrientation = Screen.orientation;
            StartCoroutine(FixSoftMasks());
        }
    }

    private static IEnumerator FixSoftMasks()
    {
        var masks =
            FindObjectsByType<SoftMask>(FindObjectsInactive.Exclude, FindObjectsSortMode.None)
                .Where(m => m.enabled)
                .ToArray();

        masks.ForEach(m => m.enabled = false);

        var wait = new WaitForEndOfFrame();
        for (var i = 0; i < 7; i++)
            yield return wait;

        //It's not guaranteed that component still exists
        masks.Where(m => m != null)
            .ForEach(m => m.enabled = true);
    }
}
```

**Comment by AlirezaTabasi7** [comment]
Any plan to fix this the proper way please? @mob-sakai

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
