### ISSUE TITLE
Revive `SoftMask.alpha` option

### ISSUE THREAD

**Issue by SeanNi1221** [mob-sakai/SoftMaskForUGUI#172]
My project relies heavily on the `SoftMask.alpha` property in SoftMask 1.x version. This property is removed in 2.0.0 and I didn' find an alternative.

This property is very useful and convenient since I don't have to iterate through each graphic child (numerous, spawned at runtime) to calculate and set there alphas one by one. I'm so confused why you removed it?

**Comment by mob-sakai** [comment]
Thank you for your reporting!
Hmmm...you're right.
I will revive that option in the near future!

**Comment by mob-sakai** [comment]
@SeanNi1221 
From my development note (2022): `SoftMask.alpha` is obsolete because it can be replaced by `CanvasGroup.alpha`.
I am working on the following:

- Add `CanvasGroup` and set `CanvasGroup.alpha` to `m_Alpha`
  - `ProjectSettings > UI > SoftMask > v2 Asset Modification`
- `SoftMask.alpha` gets/set own `CanvasGroup.alpha`

**Comment by mob-sakai** [comment]
Sorry, the idea of the modification has changed:

- `SoftMask.m_Alpha` is obsolete because it can be replaced by `Graphic.color.a`.
- Set own `Graphic.color.a` to `m_Alpha` when upgrading assets.
  - `ProjectSettings > UI > SoftMask > Upgrade All Assets V1 to V2`
- `SoftMask.alpha` will get/set its own `Graphic.color.a`
- `m_Alpha` will be not visible in the inspector
