### ISSUE TITLE
Distribute the project as a .unitypackage file

### ISSUE THREAD

**Issue by oktayturkdagli** [mob-sakai/SoftMaskForUGUI#201]
**Is your feature request related to a problem? Please describe.**

> Is there any way to distribute the project as a .unitypackage file? The release versions only have the source code of the project. If it could be downloaded as a unitypackage, it would be more flexible to share and install.

**Describe the solution you'd like**

> There are many hard coded values in the project. Most of the shaders are searched by name. But many applications have solved this problem, I don't know about the solutions but I think it is worth to talk about it.

**Describe alternatives you've considered**

> Existing alternatives are enough but this feature would add flexibility to the project.

**Comment by mob-sakai** [comment]
Thank you for your reporting!
For several reasons, we recommend using UPM instead of `.unitypackage` for installation:

- The shader include paths contain `Packages/`.
  - [Shader include path example](https://github.com/mob-sakai/SoftMaskForUGUI/blob/main/Shaders/Hidden-UI-Default-SoftMaskable.shader#L60)
- You can make `Version Defines` to use symbols.
  - [Unity Documentation on Version Defines](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html#define-symbols)
- By installing it as an embedded package, you can customize it for your project.
  - [Unity Manual on embedding packages](https://docs.unity3d.com/2022.3/Documentation/Manual/upm-embed.html)
  - [Installation instructions as an embedded package](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#install-as-embedded-package)
