### ISSUE TITLE
[v1] Doesn't work in mobile VR ?

### ISSUE THREAD

**Issue by GuillaumeCauvet** [mob-sakai/SoftMaskForUGUI#48]
Hello, I've just tried Soft Mask on a Gear VR app but it doesn't seem to work.

**Comment by mob-sakai** [comment]
Hi @GuillaumeCauvet 
Thank you for reporting.

Sorry, I didn't test on VR.
I'll test it later. :)

In your environment (VR), does it work well on editor?

**Comment by GuillaumeCauvet** [comment]
Yes, everything work perfectly in both editor and Windows (non-VR) build

Le jeu. 25 avr. 2019 à 01:42, Takashi Sakai <notifications@github.com> a
écrit :

**Comment by maskedmouse** [comment]
We're trying to use the Softmask on the Oculus GO which gives some odd visual results due to single pass stereo rendering. Looking at the shader the Softmask uses for UI it doesn't seem to implement any of the XR shader API?

I'm no shader programmer but I don't see any of the API described in the manual.
https://docs.unity3d.com/Manual/SinglePassStereoRendering.html

Not sure what I'd have to replace either.
