### ISSUE TITLE
TextMeshProUGui with Soft Maskable has TargetException

### ISSUE THREAD

**Issue by IvoCapeloMiniclip** [mob-sakai/SoftMaskForUGUI#53]
Our project isn't using the depth buffer/stencyl so we need the SoftMaskable component on UGUI to force it to mask.

Added a SoftMaskable to the TextMeshProUGUI component and it causes a Target Exception at line 314 of the SoftMaskableEditor.
m = s_FiMaterial.GetValue(spriteAsset) as Material;

**Comment by mob-sakai** [comment]
Hi @IvoCapeloMiniclip 
Thank you for your reporting!

Hmm, do you use Scriptable Render Pipeline (SRP)?

**Comment by IvoCapeloMiniclip** [comment]
Hey we do not :)

**Comment by mob-sakai** [comment]
OK, I will check it later. :)

**Comment by mob-sakai** [comment]
@IvoCapeloMiniclip 
Hmm, can you submit a reproducible minimum project for this issue?

**Comment by mob-sakai** [comment]
@IvoCapeloMiniclip 
Are you doing well?

**Comment by IvoCapeloMiniclip** [comment]
Hey sorry didn't see this the first time. hmm i just tried a blank project and the error does not happen

**Comment by mob-sakai** [comment]
👀

**Comment by IvoCapeloMiniclip** [comment]
Must be some weird combination of settings on our main project. 👎

**Comment by mob-sakai** [comment]
@IvoCapeloMiniclip 
Oh, I see.

**Comment by mob-sakai** [comment]
I am closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it is an enhancement and has not been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/mob-sakai/SoftMaskForUGUI/releases) and then please use the [issue template](https://github.com/mob-sakai/SoftMaskForUGUI/issues/new/choose). You can also contribute directly by providing a patch. :)

Thank you!
