### ISSUE TITLE
Shaders not found when using TextMeshPro as a package

### ISSUE THREAD

**Issue by oxysoft** [mob-sakai/SoftMaskForUGUI#92]
**Describe the bug**
```
Shader error in 'Hidden/TextMeshPro/Distance Field (SoftMaskable)': failed to open source file: 'Assets/TextMesh Pro/Resources/Shaders/TMPro_Properties.cginc' at line 127 (on d3d11)
Compiling Vertex program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_RGBM_ENCODING
```

**To Reproduce**
1. Import TextMeshPro and SoftMaskForUGUI from the package manager.
2. Import the TextMeshPro support for SoftMaskForUGUI.
3. Try to use a TextMeshProUGUI component with SoftMaskable.
4. Get pink text with the error above.

**Environment (please complete the following information):**
 - Version 1.0.0-preview 3
 - Platform: Editor
 - Unity version: 2019.3.14f1
 - Build options:

**Comment by mob-sakai** [comment]
You must import `TMP Essential Resources` in order to use TextMeshPro.
They include shaders, fonts, etc.

1. Select `Window > TextMeshPro > Import TMP Essential Resources` from menu  
![](https://user-images.githubusercontent.com/12690315/83823700-8bcc6e00-a70f-11ea-8177-942860b7d4f0.png)

2. Press the `Import` button in the Import dialog
![](https://user-images.githubusercontent.com/12690315/83823708-8ec75e80-a70f-11ea-87a4-be090d011563.png)

3. If the shader error is not resolved, reimport the shader.  
Or, import the `TextMeshPro Support` again.

I'll add to the readme later.
